server:
  port: 8080

spring:
  application:
    name: cronos-simple-security
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=simple-security;encrypt=false;trustServerCertificate=true
    username: sa
    password: 1q2w3e4r@#$
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect